### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mtlynch** [dvstate/minio#6]
Thanks so much for this patch. I'm excited for the merge.

I was able to upload a few files, but minio now seems to crash on every new upload attempt. Wondering if anything jumps out to you from this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xdee1d9]

goroutine 21 [running]:
github.com/minio/minio/cmd.(*SiaCacheLayer).getCacheUsed.func1(0xc420b241e0, 0x91, 0x0, 0x0, 0x1679560, 0xc420b8b770, 0x0, 0x0)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:605 +0x49
path/filepath.walk(0xc42031f2c0, 0x3e, 0x1688180, 0xc420b1e820, 0xc4205b6c80, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc420b0e360, 0x19, 0x1688180, 0xc420b07ee0, 0xc4205b6c80, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0xc4205b6ce0, 0x15, 0x1688180, 0xc4205b0b60, 0xc4205b6c80, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.walk(0x10bf702, 0xa, 0x1688180, 0xc4205b0a90, 0xc4205b6c80, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x10bf702, 0xa, 0xc4205b6c80, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
github.com/minio/minio/cmd.(*SiaCacheLayer).getCacheUsed(0xc420261180, 0x10db4ff, 0x1f)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:610 +0xd8
github.com/minio/minio/cmd.(*SiaCacheLayer).getCacheAvailable(0xc420261180, 0x0, 0x26)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:620 +0x4e
github.com/minio/minio/cmd.(*SiaCacheLayer).guaranteeCacheSpace(0xc420261180, 0x0, 0x15)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:532 +0x155
github.com/minio/minio/cmd.(*SiaCacheLayer).manager(0xc420261180)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:387 +0xb7
github.com/minio/minio/cmd.(*SiaCacheLayer).Start.func1(0xc420261180)
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:150 +0x9c
created by github.com/minio/minio/cmd.(*SiaCacheLayer).Start
        /home/mike/go/src/github.com/minio/minio/cmd/gateway-sia-cachelayer.go:152 +0xf0
```

**Comment by mtlynch** [comment]
More complete debug output: https://gist.github.com/mtlynch/b93a97506e5ecae412f8e980d5c43798

This stands out:

```
Cache space available: -18686055712
```

**Comment by mannp** [comment]
@mtlynch @dvstate mentioned on chat that he has to take out the cache now to comply with minio's PR requests, so I envisage this will have an impact here.

I too have had issues with the cache (files not being found in the cache) trying to use third party applications that are stated as compatible with minio.

Have parked it for now until the PR gets merged :)
